name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: mlv
          POSTGRES_PASSWORD: mlv
          POSTGRES_DB: meetloview
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U mlv" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: cp .env.example .env
      - run: pnpm i
      - run: pnpm prisma:generate
      - run: pnpm build
      - run: pnpm test
